### ISSUE TITLE
Metallb default ConfigMap has no data.config field

### ISSUE THREAD

**Issue by thebsdbox** [equinix/cloud-provider-equinix-metal#151]
By default the `configMap` applied by the metallb installer doesn't create the `config` key in the `data`. The CCM will report that no config exists with the name `config`... Ideally if the CCM finds the `configMap` it should be able to create the `config` KV before populating it.

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: "I'm missing"
```
