### ISSUE TITLE
The "cloud-provider-equinix-metal-kubernetes-external" service has an incorrect port

### ISSUE THREAD

**Issue by clrxbl** [equinix/cloud-provider-equinix-metal#171]
The "cloud-provider-equinix-metal-kubernetes-external" service that the CCM creates when you enable the elastic IP for control plane nodes feature creates a service on port 443, not 6443. The EIP healthcheck checks on port 6443, so it will fail unless you manually edit the service.

```
  ports:
  - name: https
    nodePort: 32373
    port: 443
    protocol: TCP
    targetPort: 6443
```

port: 443 should be changed to 6443 by default.
