### ISSUE TITLE
Additional Multiple Peers support as separate annotation for each peer value

### ISSUE THREAD

**Issue by ipochi** [equinix/cloud-provider-equinix-metal#199]
Currently Cloud Provider Equinix Metal supports multiple peers in the form of comma separated values added to the same annotatation.

e.g
```
metal.equinix.com/peer-address: 1.2.3.4,11.22.33.44
```
In the Peer autodiscovery work done by @johananl  in https://github.com/metallb/metallb/pull/593 support for multiple peers is expected in the form of separate annotations per peer IP. I'll let @johananl provide more context to the design issue at hand.

```
MetalLB can be configured to discover multiple node peers by specifying 
multiple sets of annotations/labels in the autodiscovery configuration:

peer-autodiscovery:
  from-annotations:
  - my-asn: example.com/p1-my-asn
    peer-asn: example.com/p1-peer-asn
    peer-address: example.com/p1-peer-address
  - my-asn: example.com/p2-my-asn
    peer-asn: example.com/p2-peer-asn
    peer-address: example.com/p2-peer-address
 ```
 
I think we can add additional support in CCM to have separate annotations per peer-ip such that existing downstream functionaliies are not broken and  slowly phase out/deprecate one or the other depending upon the discussion.
 
 @deitch  Please let me know your thoughts on such a change.

 /cc @iaguis

**Comment by ipochi** [comment]
This can also be extended to Peer ASNs as well which also provide comma separated values if multiple.

**Comment by johananl** [comment]
To add to the above @deitch, IMO it makes more sense to specify multiple **sets** of annotations to describe multiple peers than to specify one set of comma-separated annotations and then correlating BGP parameters based on the **position** within a string.

Consider the following:

```yaml
metal.equinix.com/peer-asns: 65001,65002,65003
metal.equinix.com/peer-ips: 10.0.0.1,10.0.0.2,10.0.0.3
```

When an entity (such as MetalLB) reads these annotations to construct BGP peers, it needs to have a "hidden context" which matches e.g. `65002` and `10.0.0.2` based on their **position** within the string. Furthermore, what happens if a value is missing for whatever reason in *one* of the annotations? We would end up with a mismatch in the number of elements :grimacing: 

IMO, the following is much clearer and safer (albeit somewhat more verbose):

```yaml
peer1.metal.equinix.com/asn: 65001
peer1.metal.equinix.com/ip: 10.0.0.1
peer2.metal.equinix.com/asn: 65002
peer2.metal.equinix.com/ip: 10.0.0.2
peer3.metal.equinix.com/asn: 65003
peer3.metal.equinix.com/ip: 10.0.0.3
```

In the context of MetalLB, adapting the peer autodiscovery feature to the comma-separated format would mean making the autodiscovery feature much less coherent. MetalLB treats a peer as an atomic unit, regardless of whether its configuration is specified in the ConfigMap or in annotations. "Hunting" for the right part of a string to figure out one parameter of a BGP peer would make the autodiscovery implementation much less coherent and more fragile IMO.

Lastly, I'd like to remind us the discussion in https://github.com/metallb/metallb/issues/682.

I realize changing the format could have an impact on backward compatibility etc. Happy to discuss this and would love to hear your thoughts! :pray:
