### ISSUE TITLE
CCM produces invalid MetalLB configuration when address sharing

### ISSUE THREAD

**Issue by jamie-34254** [equinix/cloud-provider-equinix-metal#207]
For protocols like DNS you need to listen for both UDP and TCP traffic on the same IP address. Kubernetes didn't used to support mixed protocols - although it does now: https://kubernetes.io/docs/concepts/services-networking/service/#load-balancers-with-mixed-protocol-types the common work around is to have 2 services with the same loadBalancerIP set.

MetalLB supports IP address sharing: https://metallb.universe.tf/usage/#ip-address-sharing but unfortunately when specifying 2 services with the same loadBalancerIP this causes the CCM to produce an invalid configuration for MetalLB:

```
apiVersion: v1
kind: Service
metadata:
  name: dns-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: dns-2
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: dns
  ports:
    - name: dns-tcp
      port: 53
      targetPort: dns-tcp
      protocol: TCP
  loadBalancerIP: 1.1.1.1
---
apiVersion: v1
kind: Service
metadata:
  name: dns-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: dns-2
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: dns
  ports:
    - name: dns-udp
      port: 53
      targetPort: dns-udp
      protocol: UDP
  loadBalancerIP: 1.1.1.1
```

This causes the CCM to generate:
```
- protocol: bgp
  name: dns/dns-udp
  addresses:
  - 1.1.1.1/32
  avoid-buggy-ips: false
  auto-assign: false
  bgp-advertisements: []
- protocol: bgp
  name: dns/dns-tcp
  addresses:
  - 1.1.1.1/32
  avoid-buggy-ips: false
  auto-assign: false
  bgp-advertisements: []
```

Which MetalLB sees as invalid:
```
{"caller":"k8s.go:530","configmap":"metallb-system/config","error":"CIDR \"1.1.1.1/32\" in pool \"dns/dns-udp\" overlaps with already defined CIDR \"1.1.1.1/32\"","event":"configStale","msg":"config (re)load failed, config marked stale","ts":"2021-09-24T16:09:58.682998577Z"}
{"caller":"k8s.go:530","configmap":"metallb-system/config","error":"CIDR \"1.1.1.1/32\" in pool \"dns/dns-udp\" overlaps with already defined CIDR \"1.1.1.1/32\"","event":"configStale","msg":"config (re)load failed, config marked stale","ts":"2021-09-24T16:09:58.694968353Z"}
{"caller":"k8s.go:530","configmap":"metallb-system/config","error":"CIDR \"1.1.1.1/32\" in pool \"dns/dns-udp\" overlaps with already defined CIDR \"1.1.1.1/32\"","event":"configStale","msg":"config (re)load failed, config marked stale","ts":"2021-09-24T16:09:58.700277103Z"}
{"caller":"k8s.go:530","configmap":"metallb-system/config","error":"CIDR \"1.1.1.1/32\" in pool \"dns/dns-udp\" overlaps with already defined CIDR \"1.1.1.1/32\"","event":"configStale","msg":"config (re)load failed, config marked stale","ts":"2021-09-24T16:09:58.717340121Z"}
```

**Comment by displague** [comment]
It looks like the validation that prevents this in MetalLB is here:
https://github.com/metallb/metallb/blob/9126567db61017c15f732412bd04265a2c4a5031/internal/config/config.go#L239-L250

Related issues are:
* https://github.com/metallb/metallb/issues/530
* https://github.com/metallb/metallb/issues/558

@jamie-34254 What metallb configuration would you expect to see here? What would work?

**Comment by displague** [comment]
At a glance, I wonder how important it is to differentiate address pools on protocol?

https://github.com/equinix/cloud-provider-equinix-metal/blob/5de7790e19e94d9608a42aea67631bdf6c1955b1/metal/loadbalancers/metallb/configmap.go#L408-L416

Would it make sense to ignored differences in protocol, @deitch ?

**Comment by deitch** [comment]
> Would it make sense to ignored differences in protocol, @deitch ?

The "protocol" in this case is not tcp vs udp, but metallb's conception of them, i.e. bgp vs arp. So I don't think it will help.

**Comment by deitch** [comment]
I want to make sure I understand this. The generated metallb config you show above @jamie-34254  is:

```yaml
- protocol: bgp
  name: dns/dns-udp
  addresses:
  - 1.1.1.1/32
  avoid-buggy-ips: false
  auto-assign: false
  bgp-advertisements: []
- protocol: bgp
  name: dns/dns-tcp
  addresses:
  - 1.1.1.1/32
  avoid-buggy-ips: false
  auto-assign: false
  bgp-advertisements: []
```

These are _identical_, except for the name, where one is `dns/dns-udp` and the other is `dns/dns-tcp`, based on the namespace+name of the underlying `Service`.

Is the correct metallb config for the case of dual services that share an IP to have a single address pool entry? i.e. the above really should just be something like:

```yaml
- protocol: bgp
  name: dns/dns-udp+dns/dns-tcp   # or some better amalgamated name
  addresses:
  - 1.1.1.1/32
  avoid-buggy-ips: false
  auto-assign: false
  bgp-advertisements: []
```

I definitely get the issue; I want to make sure we go down the right solution path.
