### ISSUE TITLE
metallb `nomatch` labels violate valid label spec

### ISSUE THREAD

**Issue by deitch** [equinix/cloud-provider-equinix-metal#247]
In the migration to [LoadBalancer](https://pkg.go.dev/k8s.io/cloud-provider#LoadBalancer)  spec that we did in #224 , we had to find some way for metallb to track what services are served by each upstream peer-local pairing. This allowed us to then update or remove a pairing (as expected by the cloud-provider [LoadBalancer](https://pkg.go.dev/k8s.io/cloud-provider#LoadBalancer) API.

However, metallb provides no way of tracking it, nor does it have any additional comments or unused fields in its control configmap. We eventually settled on using the `match-labels` part of the metallb configmap.

For example:

```yaml
- my-asn: 65000
  peer-asn: 65530
  peer-address: 169.254.255.1
  peer-port: 0
  source-address: 10.68.190.5
  hold-time: ""
  router-id: ""
  node-selectors:
  - match-labels:
      kubernetes.io/hostname: dc-worker-1
    match-expressions: []
  - match-labels:
      nomatch.metal.equinix.com/service-name: default/nginx-deployment
    match-expressions: []
```

Since `node-selectors` is logical OR, the label `nomatch.metal.equinix.com/service-name` never will match anything, and so will be ignored by metallb, while allowing us to use it to track services. It also prevents us from having to have a pairing entry for each service, which would make the configmap grow to an untenable size very quickly (and probably break metallb).

However, this is invalid:

```yaml
  - match-labels:
      nomatch.metal.equinix.com/service-name: default/nginx-deployment
```

If we read the [description of valid characters](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set), it says:

> Valid label value:
> 
> * must be 63 characters or less (can be empty),
> * unless empty, must begin and end with an alphanumeric character ([a-z0-9A-Z]),
> * could contain dashes (-), underscores (_), dots (.), and alphanumerics between.

That means that `nomatch.metal.equinix.com/service-name` is perfectly fine as a key, but `default/nginx-deployment` (representing the service `nginx-deployment` in the namespace `default`) is not.

This now is breaking metallb.

Thanks to @enkelprifti98 for finding this.

We need a solution.

Some possibilities:

* replace the `/` we conventionally use to separate namespace from service, with some other valid character. Unfortunately, almost all valid characters also might be part of the namespace or service. Would `default_nginx_deployment` represent the deployment `nginx_deployment` in `default`, or `deployment` in `nginx_default`?
* use the `.` to separate them, as in `default.nginx-deployment`. This only works if `.` is not valid in either namespace or service name. I'm not sure of that. The page for naming is [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/), but it isn't clear what constraints namespaces and services have.
* hash or base64 the whole thing. Since we always know what we are comparing against, any consistent forward hash/base64 should work. E.g. instead of `nomatch.metal.equinix.com/service-name: default/nginx-deployment` we could do `nomatch.metal.equinix.com/service-name-base64: ZGVmYXVsdC9uZ2lueC1kZXBsb3ltZW50`. It is ugly, but it is usable and predictable, and has precedent in kubernetes' secrets
* other ideas

Thoughts @displague @cprivite @detiber @ocobleseqx ?

**Comment by displague** [comment]
I think the following should be easy to read, manage, and convert (heal for existing records):
`nomatch.metal.equinix.com/service-name`
`nomatch.metal.equinix.com/service-namespace`

It seems conventional and not exceptional.

**Comment by deitch** [comment]
And for multiple, @displague , you are thinking this?

```yaml
- my-asn: 65000
  peer-asn: 65530
  peer-address: 169.254.255.1
  peer-port: 0
  source-address: 10.68.190.5
  hold-time: ""
  router-id: ""
  node-selectors:
  - match-labels:
      kubernetes.io/hostname: dc-worker-1
  - match-labels:
      nomatch.metal.equinix.com/service-namespace: default
      nomatch.metal.equinix.com/service-name: nginx-deployment
 - match-labels:
      nomatch.metal.equinix.com/service-namespace: ai
      nomatch.metal.equinix.com/service-name: trainer
 - match-labels:
      nomatch.metal.equinix.com/service-namespace: database
      nomatch.metal.equinix.com/service-name: mysql1
````

Like that?
