### ISSUE TITLE
MetalLB managing the control plane EIP

### ISSUE THREAD

**Issue by jhead-slg** [equinix/cloud-provider-equinix-metal#258]
I think this was not intended but with the latest v3.4.1 version and choosing MetalLB as the load balancer, it is now announcing the EIP control plane address of the `kube-system/cloud-provider-equinix-metal-kubernetes-external` service via BGP on every node. MetalLB seems not to care that the address-pool annotation is not correct.

In testing, a way to prevent this behavior is to make sure the `cloud-provider-equinix-metal-kubernetes-external` address-pool is not written to the MetalLB configmap.

I tried both MetalLB v0.11.0 and v0.12.1. Same result.

CCM controlled configmap entry:
```
    - protocol: bgp
      name: cloud-provider-equinix-metal-kubernetes-external
      addresses:
      - 136.144.xxx.xxx/32
      avoid-buggy-ips: false
      auto-assign: false
      bgp-advertisements: []
```

MetalLB controller logs:
```
metallb-controller-675fdd57f6-4tfvm controller {"caller":"level.go:63","event":"clearAssignment","level":"info","msg":"user requested a different pool than the one currently assigned","reason":"differentPoolRequested","service":"kube-system/cloud-provider-equinix-metal-kubernetes-external","ts":"2022-04-22T17:41:47.414676615Z"}
metallb-controller-675fdd57f6-4tfvm controller {"caller":"level.go:63","event":"clearAssignment","level":"info","msg":"user requested a different IP than the one currently assigned","reason":"differentIPRequested","service":"kube-system/cloud-provider-equinix-metal-kubernetes-external","ts":"2022-04-22T17:41:47.414818205Z"}
metallb-controller-675fdd57f6-4tfvm controller {"caller":"level.go:63","event":"ipAllocated","ip":"136.144.xxx.xxx","level":"info","msg":"IP address assigned by controller","service":"kube-system/cloud-provider-equinix-metal-kubernetes-external","ts":"2022-04-22T17:41:47.414922627Z"}
```
