### ISSUE TITLE
MetalLB not assigning LoadBalancer IPs to services in a different namespace

### ISSUE THREAD

**Issue by enkelprifti98** [equinix/cloud-provider-equinix-metal#286]
It looks like when a user has at least 1 LoadBalancer service inside a specific namespace and creates another LoadBalancer service in a different namespace, MetalLB will not be able to assign an IP from the address pool. So it seems to somehow stick to only a single namespace, whichever namespace you start creating services inside first.

I am not sure if this is an issue of the CCM not building the MetalLB configmap in the right format or if it's a MetalLB bug.

The CCM will do its job fine, it will see that a new service has been requested, gets an Elastic IP and adds the address pool to the MetalLB configmap, but then MetalLB controller throws this error: (147.28.147.200 is the IP allocated for the service in the different namespace)

```
{"caller":"level.go:63","error":"[\"147.28.147.200\"] is not allowed in config","level":"error","msg":"IP allocation failed","op":"allocateIPs","service":"test/nginx-deployment","ts":"2022-05-26T10:12:10.84053692Z"}
```

Here is what the address pools section looks like in the configmap:

```
address-pools:
- protocol: bgp
  name: nginx-deployment
  addresses:
  - 147.28.147.80/32
  avoid-buggy-ips: false
  auto-assign: false
  bgp-advertisements: []
- protocol: bgp
  name: nginx-deployment
  addresses:
  - 147.28.147.200/32
  avoid-buggy-ips: false
  auto-assign: false
  bgp-advertisements: []
```
