### ISSUE TITLE
Improve EIP/VIP failover when the node running CPEM fails

### ISSUE THREAD

**Issue by cprivitere** [equinix/cloud-provider-equinix-metal#304]
Right now in a cluster with an HA control plane using CPEM for EIP management you can have the following situation.

### Situation
3-controlplane-node Kubernetes cluster, created with CAPP. Has CPEM, with the control plane EIP pointing at one of the nodes (not kube-vip or metallb, but rather CPEM’s direct control), CPEM running on the same node that EIP is pointing to.
CP nodes
  A    <--- EIP ; CPEM here
  B
  C (edited) 

Node A goes away.

CPEM should move the EIP to node B or C. But CPEM is gone too, so it cannot do so until k8s controllers move it to node B.
Problem: It never happens. Controller and scheduler never seem to learn that it has something to do, CPEM stays dead, EIP never moves, we are stuck.
What does work: Each CP node’s controller-manager and scheduler do point at their local IP kube-apiserver, which in turn points at the local etcd.

###Root cause
kubelet. /etc/kubernetes/kubelet.conf points to the EIP:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data:  // etc. etc.
    server: https://1.2.3.4:6443/      // <===== this is the EIP, not the local
  name: default-cluster
```

So all of the components are working, but the kubelets cannot connect to the apiserver, so controllers do not actually know what the state of anything is.
