### ISSUE TITLE
cloud-controller-manager in crashloop due to nil pointer exception

### ISSUE THREAD

**Issue by schrodit** [equinix/cloud-provider-equinix-metal#359]
cloud controller crashes in `github.com/equinix/cloud-provider-equinix-metal/metal.getMetalConfig` due to a nil pointer exception:
```
I0127 09:05:49.125494       1 serving.go:348] Generated self-signed cert in-memory
W0127 09:05:55.522563       1 authentication.go:423] failed to read in-cluster kubeconfig for delegated authentication: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
W0127 09:05:55.522602       1 authorization.go:226] failed to read in-cluster kubeconfig for delegated authorization: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
W0127 09:05:55.522616       1 authorization.go:194] No authorization-kubeconfig provided, so SubjectAccessReview of authorization tokens won't work.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4b0cd4]

goroutine 1 [running]:
io.ReadAll({0x0, 0x0})
	/usr/local/go/src/io/io.go:661 +0xd4
io/ioutil.ReadAll(...)
	/usr/local/go/src/io/ioutil/ioutil.go:27
github.com/equinix/cloud-provider-equinix-metal/metal.getMetalConfig({_, _})
	/workspace/metal/config.go:100 +0xbd
github.com/equinix/cloud-provider-equinix-metal/metal.init.0.func1({0x0?, 0x0?})
	/workspace/metal/cloud.go:51 +0x5d
k8s.io/cloud-provider.GetCloudProvider({0x7ffecbf0a79e?, 0x8?}, {0x0, 0x0})
	/go/pkg/mod/k8s.io/cloud-provider@v0.25.0/plugins.go:86 +0xf9
k8s.io/cloud-provider.InitCloudProvider({0x7ffecbf0a79e, 0xc}, {0x0?, 0x8?})
	/go/pkg/mod/k8s.io/cloud-provider@v0.25.0/plugins.go:164 +0x2c5
main.cloudInitializer(0xc00011c820)
	/workspace/main.go:57 +0x4c
k8s.io/cloud-provider/app.NewCloudControllerManagerCommand.func1(0xc000004a00?, {0xc000145590?, 0x5?, 0x5?})
	/go/pkg/mod/k8s.io/cloud-provider@v0.25.0/app/controllermanager.go:88 +0x1e9
github.com/spf13/cobra.(*Command).execute(0xc000004a00, {0xc00011e130, 0x5, 0x5})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004a00)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/workspace/main.go:48 +0x2cc
```

Do I miss a critical config?

my deployment looks like:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud-controller-manager
  name: cloud-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-controller-manager
  template:
    metadata:
      annotations:
        checksum/secret-cloudprovider: 90174e466bb73b0d9c3090e0fe4466ee0ba63cd4f2146562cabd422f96fde3f2
      labels:
        app: cloud-controller-manager
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - ./cloud-provider-equinix-metal
        - --cloud-provider=equinixmetal
        - --leader-elect=false
        - --allow-untagged-cloud=true
        - --authentication-skip-lookup=true
        - --kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
        env:
        - name: METAL_API_KEY
          valueFrom:
            secretKeyRef:
              key: apiToken
              name: cloudprovider
        - name: METAL_PROJECT_ID
          valueFrom:
            secretKeyRef:
              key: projectID
              name: cloudprovider
        - name: METAL_METRO_NAME
          value: fr
        - name: METAL_LOAD_BALANCER
          value: metallb:///
        image: docker.io/equinix/cloud-provider-equinix-metal:v3.5.0
        imagePullPolicy: IfNotPresent
        name: cloud-provider-equinix-metal
        ports:
        - containerPort: 10253
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
          name: kubeconfig
          readOnly: true
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - name: kubeconfig
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: kubeconfig
                path: kubeconfig
              name: generic-token-kubeconfig
              optional: false
          - secret:
              items:
              - key: token
                path: token
              name: shoot-access-cloud-controller-manager
              optional: false
```
