### ISSUE TITLE
[MetalLB] RBAC not allowing CPEM to work with metallb.io resources

### ISSUE THREAD

**Issue by Lirt** [equinix/cloud-provider-equinix-metal#388]
Hi again,

After [latest patch for MetalLB](https://github.com/equinix/cloud-provider-equinix-metal/pull/386) there is missing RBAC. CPEM cannot list/create or other verbs on resources from apiGroup `metallb.io`.

Updating ClusterRole (installed from helm chart) `system:cloud-controller-manager` with following additional config helped:

```yaml
- apiGroups:
  - metallb.io
  resources:
  - ipaddresspools
  - bgppeers
  - bgpadvertisements
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
```
